### ISSUE TITLE
"checked" prop does not represent whether or not the box is checked

### ISSUE THREAD

**Issue by danerbrear** [WrathChaos/react-native-rounded-checkbox#1]
Updating the "isChecked" prop does not reflect wether or not the box is actually checked

`<RoundedCheckbox 
                            isChecked={isSelectedState}
                            text=""
                            component={<Icon name="check" size={18} color={BASIC_COLORS.white}/>}
                            checkedColor={BASIC_COLORS.systemBlue}
                            outerSize={30}
                            innerSize={25}/>`

I can confirm `isSelectedState` changes appropriately and as intended, however the rounded checkbox never becomes checked when the state changes.

**Comment by kuraydev** [comment]
Hello @danerbrear,
Thank you for the reporting.

I could not reproduce this problem. Have you tried [the example](https://github.com/WrathChaos/react-native-rounded-checkbox/tree/master/example) project? It works on my side. If there is still a problem, can you please share with me a reproducible example?
