### ISSUE TITLE
Does the component prop still exist?

### ISSUE THREAD

**Issue by AhmadHoranieh** [WrathChaos/react-native-rounded-checkbox#2]
After I upgraded my SDK, and all dependencies, my RoundedCheckbox component stopped showing icons present in the component prop. Was this prop removed, or what is the issue exactly?

`<RoundedCheckbox
                                                uncheckedColor = {measurement_inactive_button_circle}
                                                checkedTextColor = {measurement_active_button_circle}
                                                outerSize = {deviceWidth * 13/100}
                                                innerSize = {deviceWidth * 10/100}
                                                active = {this.state.export_journey}
                                                onPress={() => {this.state.export_journey ? this.setState({export_journey: false}) : this.setState({export_journey: true})}}
                                                component = {<SimpleLineIcons name="graph" size={deviceWidth * 8/100} color={measurement_icon_colour} />}
                                                />`

Should I roll back to a previous version?

**Comment by AhmadHoranieh** [comment]
I just read the update logs and it seems that icons should be put as the direct child of the component. I apologise, I will be closing the issue now.

**Comment by kuraydev** [comment]
If you need anything please open an issue :) @Mextliy
